Number tasks
NikolayKovzik/js-internship pull request #1
Opened 2023-02-07 09:08 UTC by NikolayKovzik

Solved all tasks from the file "numbers-tasks".

2023-02-09 09:32 UTC, echonok requested changes

2023-02-09 09:32 UTC, echonok commented on js/practice/task/02-numbers-tasks.js
> +    return x === -0 ? 0 : x;
why do we compare the result (x) with -0? What is even '-0'?

2023-02-09 09:32 UTC, echonok commented on js/practice/task/02-numbers-tasks.js
> +        (n % div == 0) ? isNumPrime = false : ++div;
OK, but some people think that it's a bad practice. We use the ternary operator for returning a value, not for anything else
Like in these examples

2023-02-09 16:03 UTC, NikolayKovzik commented on js/practice/task/02-numbers-tasks.js
> +    return x === -0 ? 0 : x;
I agree, it looks ugly) I couldn't figure out how to get around the test, which crashed due to the comparison of -0 and 0.
Fixed it.

2023-02-09 16:03 UTC, NikolayKovzik commented on js/practice/task/02-numbers-tasks.js
> +        (n % div == 0) ? isNumPrime = false : ++div;
Thanks, fixed

2023-02-10 08:17 UTC, echonok approved these changes

2023-02-10 09:17 UTC, merged