Strings tasks
NikolayKovzik/js-internship pull request #2
Opened 2023-02-07 09:10 UTC by NikolayKovzik

solved all tasks from the file "strings-tasks"

2023-02-09 09:33 UTC, echonok requested changes

2023-02-09 09:33 UTC, echonok commented on js/practice/task/01-strings-tasks.js
> +    const cards = [
Let's make it more interesting: please create the cards dynamically. So that if we add a new symbols we won't need to repeat actions.

2023-02-09 16:32 UTC, NikolayKovzik commented on js/practice/task/01-strings-tasks.js
> +    const cards = [
Do you mean to implement a function that looks for absolutely any character in the passed array?

2023-02-14 11:24 UTC, NikolayKovzik commented on js/practice/task/01-strings-tasks.js
> +    const cards = [
done

2023-02-15 08:35 UTC, echonok approved these changes

2023-02-15 08:35 UTC, echonok commented on js/practice/task/01-strings-tasks.js
> +    const cards = [
Nope. You have 4 MARK symbols (♣, ♦, ♥, and ♠) and 13 NUMBER symbols (2, 3, 4 ...). What if we need to add a new MARK symbol and remove one NUMBER symbol? You need to change `cards` by hand. It's better to have two arrays and generate a new one (card) initially.

2023-02-15 09:20 UTC, merged