Arrays tasks
NikolayKovzik/js-internship pull request #4
Opened 2023-02-08 11:16 UTC by NikolayKovzik

solved all tasks from the file "arrays-tasks"

2023-02-09 09:27 UTC, echonok requested changes

2023-02-09 09:27 UTC, echonok commented on js/practice/task/04-arrays-tasks.js
> +  return arr.reduce((res, item) => typeof item === 'number' && item > 0 ? res + 1 : res, 0);
`reduce` is more consumable operation. Here we can use `filter`

2023-02-09 15:40 UTC, NikolayKovzik commented on js/practice/task/04-arrays-tasks.js
> +  return arr.reduce((res, item) => typeof item === 'number' && item > 0 ? res + 1 : res, 0);
Yes, I overcomplicated the solution. Fixed it

2023-02-10 08:23 UTC, echonok approved these changes

2023-02-10 09:18 UTC, merged