Date tasks
NikolayKovzik/js-internship pull request #5
Opened 2023-02-08 13:10 UTC by NikolayKovzik

solved all tasks from the file "date-tasks"

2023-02-09 09:34 UTC, echonok requested changes

2023-02-09 09:34 UTC, echonok commented on js/practice/task/03-date-tasks.js
> +  return `${hours.length === 1 ? `0${hours}` : hours}:`
Too complex to understand at first glance. It's better to use constants. The return should be just a concatenation of their values.
Besides, constructions like
```
if (...) {
  if (...) {
    ....
  } else {
  ...
} else {
  ...
  }
}
```
or

`... ? ... ? ... : ... : ...`
consume too much time to figure out what is going on

Please, refine this :)

2023-02-09 15:34 UTC, NikolayKovzik commented on js/practice/task/03-date-tasks.js
> +  return `${hours.length === 1 ? `0${hours}` : hours}:`
Thanks! I've fixed this

2023-02-10 08:19 UTC, echonok approved these changes

2023-02-10 09:15 UTC, merged